### ISSUE TITLE
Training Meso4

### ISSUE THREAD

**Issue by abnishstha** [DariusAf/MesoNet#10]
Hi @DariusAf 
Can you share with us code how did you train your models Meso4.

Thanks.

**Comment by DariusAf** [comment]
Hi, you can find the code [on this issue](https://github.com/DariusAf/MesoNet/issues/4#issuecomment-448694527) with the exact parameters used for data augmentation. From there, you can loop on `next(generator)` or use `fit_generator`.

Hope that helps,
