### ISSUE TITLE
I want to ask you for the data set

### ISSUE THREAD

**Issue by leffey** [DariusAf/MesoNet#11]
I am very interested in the project you are working on, but lack training data. I want to ask you for the data set. Thank you

**Comment by 1582dyd** [comment]
> 
> 
> I am very interested in the project you are working on, but lack training data. I want to ask you for the data set. Thank you

Sorry to disturb, have you got the data set?

**Comment by DariusAf** [comment]
Yes, send me an email, I will give you a download link for the dataset. The adress is on the paper.
