### ISSUE TITLE
Deepfake dataset

### ISSUE THREAD

**Issue by jmpu** [DariusAf/MesoNet#16]
Hi Darius,

I am currently working on a Deepfake-related project. Would you be able to share the Deepfake dataset you collected? I have sent you an email.

**Comment by DariusAf** [comment]
Hi,
I have just updated the readme with the link!

**Comment by Uhouhzam** [comment]
Hi Darius, 

I have used your dataset for my deepfake detection project. Could you tell the origine of your data set ? What kind of deepfake data set does it belong to ?  It belongs to  one of four dataset : Face- Forensics++ database , UADFV database, Diverse Fake Face Database (DFFD) , Deepfakes Detection Challenge (DFDC) database ? or It belongs none of them ?  
Also for the real image data set , does it belong to  FlickrFaces-HQ (FFHQ), CelebA , original of FaceForensics++ data ?

**Comment by DariusAf** [comment]
The deepfake datasets you mention did not exist at the time of our paper (2018).

Our fake images originated from the few existing videos I manually collected online that were forged with deepfake technique. And the real videos are from interviews of many people around the world. We extracted faces from the videos and did not publish them to avoid spreading fake content, which made sense at that time.

**Comment by Uhouhzam** [comment]
Thank you for your answer. 
Do you remember what kind deepfake technique they used to produce the existing video ?  Is it as same as the deepfake technique presented in your paper (2018)?

**Comment by DariusAf** [comment]
Right, the "original" deepfake technique with two autoencoders. The dataset was introduced in that paper, so yes, we cannot update it for reproducibility.

**Comment by Uhouhzam** [comment]
Ok . Thank you very much. I got all I want to know.
