### ISSUE TITLE
a request for Dataset 

### ISSUE THREAD

**Issue by leichen2** [DariusAf/MesoNet#17]
Dear Darius:
    I am a undergraduate from Beijing Univeraity of Chemical Technology,China, Currenty I want to begin my personal research in Deepfake Detection because of my interest，I really admire to your algorithm in this paper and want to run your code，so would you pleased sent me your dataset？I would appreciate it if you send me your dataset！！My email aderss is [buctlchen@qq.com].Thank you very much!BEST WISHES!

**Comment by amuchand47** [comment]
Please share the datasets with me at amuchad47@gmail.com.

**Comment by DariusAf** [comment]
I have just (finally) updated the readme with the link!
