### ISSUE TITLE
Dataset Variety

### ISSUE THREAD

**Issue by Valentino-L** [DariusAf/MesoNet#37]
Are your deepfake images (from training dataset) generated using autoencoders? Currently GAN (Generative adversarial networks) and diffusion model (for example DDPM) are also popular to generate deepfake images/videos. How accurate do you think your model is when detecting GAN or diffusion model generated deepfakes? 

Many thanks!

**Comment by DariusAf** [comment]
Well, this paper was written in 2018 and diffusion models didn't exist at that time, and GANs were seldom used for face-swapping. So we mostly focused on what was available at that time: autoencoders.

I cannot make claims on how good it extrapolate to this latter methods and whether it needs specific retraining (but wouldn't be surprised that it does), this needs to be tested. Or check more recent research contributions!

Darius
